### ISSUE TITLE
message UI

### ISSUE THREAD

**Issue by Flowy** [mcd8604/wowmessagebarker#18]
will it be possible to add some UI to allow 'real time' messaging
bonus points for making it hide/show
max points for making it possible from titan panel (data broker https://github.com/tekkub/libdatabroker-1-1 )
tbh, I care only about titan panel integration

to be clear, the point is having buttons on screen that are able to post predefined messages

**Comment by mcd8604** [comment]
are you talking about a compact view that shows just the "send" buttons for easy access?
this is a feature that I have been thinking about adding, but haven't had the time to do yet

**Comment by mcd8604** [comment]
Closing this issue now, as the enhancement is under #21
