### ISSUE TITLE
[request] [option] no minimap button

### ISSUE THREAD

**Issue by waytoomuchgaming** [mcd8604/wowmessagebarker#19]
Titan Panel recognize it, btw.

Also maybe, add a command line to launch the message barker window ? (i guess it already exist, but i don't know it)

**Comment by mcd8604** [comment]
Once I add an configuration/settings menu, I will add the option to hide the minimap button.
There actually is not a slash command to open the window. I will add one eventually.

**Comment by mcd8604** [comment]
v0.3.3 release now includes these - see Readme for commands
