### ISSUE TITLE
[request] options when right clicking the button (on minimap, or on titan panel)

### ISSUE THREAD

**Issue by Altoholic** [mcd8604/wowmessagebarker#20]
I would like to have a drop-down menu with all the messages i created (only their title, or even just their number) with right click, and the "send" action when i left click on one of them, so i can avoid loading the full addon window AND avoid using keybinds (i already use a ton of them ^^).

**Comment by mcd8604** [comment]
Yes, this is a good idea (one which I also had but haven't had the time to do yet. Once I can spare some time, I will start working on it. Closing this issue now, as the enhancement is under #21
