### ISSUE TITLE
No longer works on latest SOM game client update 2/8/2022

### ISSUE THREAD

**Issue by khenzel** [mcd8604/wowmessagebarker#22]
LUA error on init line 10:

MessageBarker:RegisterCallback(MessageBarkerEvent.Initialized, function(event) self:Initialize() end)

registration of MessageBarkerEvent failure. 

Please correct.

**Comment by mcd8604** [comment]
fixed in 7941014d47af8c70bc606ed29b2bc5248c98f8c3
