### ISSUE TITLE
Lua Error in BCC when placing items from inventory into open spot of gbank

### ISSUE THREAD

**Issue by Calyus** [mcd8604/wowmessagebarker#23]
When I disable Message Barker it works without issue. But when its enabled I am not able to place items into the gbank at all. 

![image](https://user-images.githubusercontent.com/95837345/174667966-8483c1b3-46af-4e4c-8e52-94ddf1000c67.png)

**Comment by mcd8604** [comment]
Thanks for this report, I wouldn't have known about it otherwise. It should be fixed in the next release.
