### ISSUE TITLE
Errors with current Retail

### ISSUE THREAD

**Issue by layzsmurf** [mcd8604/wowmessagebarker#24]
Message Barker does not warn about a maximum Message size:

`4x SendChatMessage(): Chat message limits exceeded
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@MessageBarker/MessageBarker.lua"]:41: in function `BarkMessage'
[string "@MessageBarker/MessageRow.lua"]:70: in function `RunClicked'
[string "*MessageRow.xml:50_OnClick"]:1: in function <[string "*MessageRow.xml:50_OnClick"]:1>

Locals:
(*temporary) = "[... Deleted]"
(*temporary) = "CHANNEL"
(*temporary) = nil`

XML Errors:
* `409x MessageBarker/MessageTemplates/MessageTemplates.xml:10 Unrecognized XML attribute: val`
* `443x MessageBarker/MessageTemplates/MessageTemplates.xml:10 Unrecognized XML: AbsValue`
* `448x MessageBarker/MessageTemplates/MessageTemplates.xml:9 Unrecognized XML: TileSize`
* `448x MessageBarker/MessageTemplates/MessageTemplates.xml:7 Unrecognized XML attribute: val`
* `448x MessageBarker/MessageTemplates/MessageTemplates.xml:7 Unrecognized XML: AbsValue`
* `448x MessageBarker/MessageTemplates/MessageTemplates.xml:5 Unrecognized XML attribute: bgFile`
*

**Comment by mcd8604** [comment]
fixed in 5002da9
