### ISSUE TITLE
[bug][classic ERA] can't send message to General

### ISSUE THREAD

**Issue by waytoomuchgaming** [mcd8604/wowmessagebarker#26]
All the other channels work fine, including say and yell. But nothing goes on General.
I quit and go back to general, just to be sure, but that does nothing.
No lua error.

Update: LocalDefense also unavailable.
And something weird in the base UI: 
![bug](https://github.com/mcd8604/wowmessagebarker/assets/336778/09a7f3ec-e8b7-4a1b-9ffc-0bbce68a4596)

**Comment by mcd8604** [comment]
I just tested on all clients and all of the channels are working properly.
![image](https://github.com/mcd8604/wowmessagebarker/assets/2568468/3368792f-2426-4567-908b-9af0f1147c0c)
Are you sure that you're in the channels when you send the message? If General is showing up with a Join button, I think that means you're not actually joined to it. The weird thing is that General doesn't show up in both spots on my clients, maybe you have encountered a bug in the client itself:
![image](https://github.com/mcd8604/wowmessagebarker/assets/2568468/b69623ac-d4fd-44a6-a900-b17f27aa0c64)

**Comment by waytoomuchgaming** [comment]
More tests: 
* the addon can't send messages in  channels where the join button is still present, despite the fact that i'm allready joined in.
* i can send messages myself in said channels

It feels like a base UI bug, but strangely, it's working - except for the addon.

**Comment by mcd8604** [comment]
closing as there is no reproducible bug here
